### ISSUE TITLE
Watchify transform failing with reactify on error

### ISSUE THREAD

**Issue by gregtatum** [andreypopp/reactify#18]
https://github.com/substack/watchify/issues/64

I'm running into this issue from Watchify which was closed because their tests passed, even though the error still seems to be there. I'm wondering if it's something in the implementation with Reactify.

Terminal output:

```
[14:09:51] Using gulpfile /MyWebsite/gulpfile.js
[14:09:51] Starting 'watch'...
[14:09:51] Bundle rebuilt
[14:09:51] Finished 'watch' after 15 ms
[14:09:51] Starting 'default'...
[14:09:51] Finished 'default' after 4.53 μs

events.js:72
        throw er; // Unhandled 'error' event
              ^
ReactifyError: /MyWebsite/js/components/SearchDeals.jsx: Parse Error: Line 22: Expected corresponding XJS closing tag for h2 while parsing file: /MyWebsite/js/components/SearchDeals.jsx
    at throwError (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2343:21)
    at parseXJSElement (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5998:17)
    at parseXJSChild (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5920:21)
    at parseXJSElement (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5992:31)
    at parseXJSChild (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5920:21)
    at parseXJSElement (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5992:31)
    at parsePrimaryExpression (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2906:20)
    at parseLeftHandSideExpressionAllowCall (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2990:61)
    at parsePostfixExpression (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3030:20)
    at parseUnaryExpression (/MyWebsite/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3097:16)
```

package.json versions I'm running

```
{
  "name": "mywebsite",
  "version": "0.0.1",
  "devDependencies": {
    "browserify": "^5.10.0",
    "gulp": "^3.8.7",
    "gulp-jshint": "^1.8.4",
    "gulp-react": "^1.0.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^0.7.3",
    "gulp-sourcemaps": "^1.1.1",
    "gulp-uglify": "^0.3.1",
    "gulp-util": "^3.0.0",
    "jshint-stylish": "^0.4.0",
    "minifyify": "^4.0.4",
    "reactify": "^0.14.0",
    "vinyl-source-stream": "^0.1.1",
    "watchify": "^1.0.5"
  },
  "dependencies": {
    "underscore": "^1.7.0"
  }
```

**Comment by anilsambasivan** [comment]
check if you are closing tag "h2" in same small letters
