### ISSUE TITLE
Watchify fails with reactify

### ISSUE THREAD

**Issue by eyscode** [andreypopp/reactify#61]
I'm using browserify, watchify and reactify in a project, browserify runs perfect, but watchify is failing, I think could be a problem of reactify or watchify, I'm reporting the issue here and watchify github, the watcher is initiated by npm start in package.json as follows:

```
{...
  "scripts": {
    "start": "watchify -o js/bundle.js -v -d js/app.js",
    "build": "browserify . -t [envify --NODE_ENV production] | uglifyjs -cm > js/bundle.min.js",
    "test": "jest"
  },
  "browserify": {
    "transform": [
      "reactify",
      "envify"
    ],
...}
```

Terminal output:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch ENOSPC
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at createFsWatchInstance (/miranda_frontend/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/miranda_frontend/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:80:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/miranda_frontend/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/miranda_frontend/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/miranda_frontend/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at Object.oncomplete (fs.js:107:15)
```

**Comment by andreypopp** [comment]
ENOSPC usually means you have no space on your drive.

**Comment by eyscode** [comment]
That was weird, I just restart the pc and it worked. I think my PC became crazy for a moment. Whatever, thanks for the help! :+1:
