### ISSUE TITLE
Error: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by sungwoncho** [andreypopp/reactify#71]
Using gulp, I am trying to reactify my javascript files. But I get `Arguments to path.resolve must be strings` exception.

```javascripts
var gulp = require('gulp');
var reactify = require('reactify');

gulp.task('js', function () {
  return gulp.src('/public/javascripts/src/*.jsx')
    .pipe(reactify())
    .pipe(gulp.dest('/public/javascripts/dist'))
});
```

When I comment out `.pipe(reactify())`, I don't get that error. Any suggestions?

Full error:
```
[11:08:34] Using gulpfile ~/Development/Github/express-react-todo/gulpfile.js
[11:08:34] Starting 'js'...
path.js:422
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at DestroyableTransform.saveFile [as _transform] (/Users/mikecho/Development/Github/express-react-todo/node_modules/gulp/node_modules/vinyl-fs/lib/dest/index.js:36:26)
    at DestroyableTransform.Transform._read (/Users/mikecho/Development/Github/express-react-todo/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mikecho/Development/Github/express-react-todo/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mikecho/Development/Github/express-react-todo/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/mikecho/Development/Github/express-react-todo/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/mikecho/Development/Github/express-react-todo/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at drain (/Users/mikecho/Development/Github/express-react-todo/node_modules/reactify/node_modules/through/index.js:36:16)
```

**Comment by ORESoftware** [comment]
+1

**Comment by andreypopp** [comment]
`reactify` is a browserify transform. Not sure if it can be used with `gulp.src`.

**Comment by ORESoftware** [comment]
this answer helped me, it might help the OP as well https://github.com/gulpjs/gulp/issues/1186#issuecomment-127426422
